# Generated by Django 4.1.13 on 2024-03-31 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unid_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GW2_Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=200)),
                ('venter_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GW2_Recipes',
            fields=[
                ('id', models.IntegerField()),
                ('output_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('output_item_count', models.IntegerField()),
                ('ingredients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GW2_Trading_Post_Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('buys', models.JSONField()),
                ('sells', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Processed_User_Storage',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid_processing.gw2_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_User_Storage',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid_processing.gw2_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Default_Salvage_Rates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('salvage_rate', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unid_processing.gw2_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_User_Bank_Data',
            fields=[
                ('raw_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.raw_user_storage')),
            ],
            bases=('unid_processing.raw_user_storage',),
        ),
        migrations.CreateModel(
            name='Raw_User_Inventory_Data',
            fields=[
                ('raw_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.raw_user_storage')),
            ],
            bases=('unid_processing.raw_user_storage',),
        ),
        migrations.CreateModel(
            name='Raw_User_Shared_Inventory_Data',
            fields=[
                ('raw_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.raw_user_storage')),
            ],
            bases=('unid_processing.raw_user_storage',),
        ),
        migrations.CreateModel(
            name='User_Bank',
            fields=[
                ('processed_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.processed_user_storage')),
            ],
            bases=('unid_processing.processed_user_storage',),
        ),
        migrations.CreateModel(
            name='User_Default_Blue_Salvage_Rates',
            fields=[
                ('user_default_salvage_rates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.user_default_salvage_rates')),
            ],
            bases=('unid_processing.user_default_salvage_rates',),
        ),
        migrations.CreateModel(
            name='User_Default_Green_Salvage_Rates',
            fields=[
                ('user_default_salvage_rates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.user_default_salvage_rates')),
            ],
            bases=('unid_processing.user_default_salvage_rates',),
        ),
        migrations.CreateModel(
            name='User_Default_Yellow_Salvage_Rates',
            fields=[
                ('user_default_salvage_rates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.user_default_salvage_rates')),
            ],
            bases=('unid_processing.user_default_salvage_rates',),
        ),
        migrations.CreateModel(
            name='User_Inventory',
            fields=[
                ('processed_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.processed_user_storage')),
            ],
            bases=('unid_processing.processed_user_storage',),
        ),
        migrations.CreateModel(
            name='User_Materials',
            fields=[
                ('processed_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.processed_user_storage')),
            ],
            bases=('unid_processing.processed_user_storage',),
        ),
        migrations.CreateModel(
            name='User_Shared_Inventory',
            fields=[
                ('processed_user_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unid_processing.processed_user_storage')),
            ],
            bases=('unid_processing.processed_user_storage',),
        ),
        migrations.AddField(
            model_name='gw2_items',
            name='item_recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='unid_processing.gw2_recipes'),
        ),
        migrations.AddField(
            model_name='gw2_items',
            name='item_tp_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='unid_processing.gw2_trading_post_data'),
        ),
    ]
