# Generated by Django 5.0.4 on 2024-07-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unid_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_salvage_rates',
            unique_together={('user', 'gained_item_id')},
        ),
    ]
