# Generated by Django 5.0.4 on 2024-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid_processing', '0002_rename_venter_value_gw2_items_vender_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_salvage_records',
            name='salvaged_item_count',
            field=models.IntegerField(default=0),
        ),
    ]
