# Generated by Django 5.0.4 on 2024-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid_processing', '0003_user_salvage_records_salvaged_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_outcome_data',
            name='gained_item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_outcome_data',
            name='gained_item_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
